{% set name = "klib" %}
{% set version = "0.0.70" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: acc512d8d33f4d4c3594a1ce45c2e7df6cfd8703132ce3dec378c274522370a1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - matplotlib-base >=2.1.2
    - numpy >=1.13.3
    - pandas >=1.0.0
    - seaborn >=0.1.0
  run:
    - matplotlib-base >=2.1.2
    - numpy >=1.13.3
    - pandas >=1.0.0
    - python >=3.6
    - seaborn >=0.1.0

test:
  imports:
    - klib
    - klib.tests

about:
  home: https://github.com/akanz1/klib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Customized data preprocessing functions for frequent tasks.
  dev_url: https://github.com/akanz1/klib

extra:
  recipe-maintainers:
    - akanz1
