{% set name = "klib" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d786822c06e4c962595209c8ada890d8902fa227dacd4ce1f28231ea53122e17

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - poetry-core >=1.0.7,<1.1.0
    - matplotlib >=3.0.3
    - numpy >=1.16.3
    - pandas >=1.1.2
    - seaborn >=0.11.1
    - scipy >=1.1.0
  run:
    - python >=3.7
    - matplotlib-base >=3.0.3
    - numpy >=1.16.3
    - pandas >=1.1.2
    - seaborn >=0.11.1
    - scipy >=1.1.0

test:
  source_files:
    - tests
  imports:
    - klib

about:
  home: https://github.com/akanz1/klib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Customized data preprocessing functions for frequent tasks.
  dev_url: https://github.com/akanz1/klib

extra:
  recipe-maintainers:
    - akanz1
