{% set name = "klib" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9b2e2098cbda3fce8df8e333832a4b3bb251660055642006bc95bc8262f4cfd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - matplotlib >=3.0.3
    - numpy >=1.16.3
    - pandas >=1.1.2
    - seaborn >=0.11.1
    - scikit-learn >=0.23.1
    - scipy >=1.1.0
  run:
    - python >=3.7
    - matplotlib-base >=3.0.3
    - numpy >=1.16.3
    - pandas >=1.1.2
    - seaborn >=0.11.1
    - scikit-learn >=0.23.1
    - scipy >=1.1.0

test:
  imports:
    - klib
    - klib.tests

about:
  home: https://github.com/akanz1/klib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Customized data preprocessing functions for frequent tasks.
  dev_url: https://github.com/akanz1/klib

extra:
  recipe-maintainers:
    - akanz1
