{% set name = "klib" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 504e12d51ba929fcd7fd1da8a769b1070099411d62e3e5099dc45548e08838db

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - matplotlib >=3.0.3
    - numpy >=1.15.4
    - pandas >=1.0.5
    - seaborn >=0.10.1
    - scikit-learn >=0.23
    - scipy >=1.0.0
  run:
    - python >=3.7
    - matplotlib-base >=3.0.3
    - numpy >=1.15.4
    - pandas >=1.0.5
    - seaborn >=0.10.1
    - scikit-learn >=0.23
    - scipy >=1.0.0

test:
  imports:
    - klib
    - klib.tests

about:
  home: https://github.com/akanz1/klib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Customized data preprocessing functions for frequent tasks.
  dev_url: https://github.com/akanz1/klib

extra:
  recipe-maintainers:
    - akanz1
