{% set name = "klib" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5bb5fc23597841135aa641a7aa3b7d277524d7b2f2f3736facfbd6c5ee7898ac

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - poetry-core
  run:
    - matplotlib-base >=3.6.0
    - numpy >=1.26.0
    - pandas >=1.4.0
    - plotly >=5.11.2
    - python >=3.9
    - scipy >=1.10.0
    - screeninfo >=0.8.1
    - seaborn >=0.12.0

test:
  source_files:
    - tests
  imports:
    - klib

about:
  home: https://github.com/akanz1/klib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easy to use Python library of customized functions for cleaning and analyzing data.
  dev_url: https://github.com/akanz1/klib

extra:
  recipe-maintainers:
    - akanz1
