{% set name = "klib" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05fc49a5b6c688a060e6d2dd2dc9c62a9dd685dd00f550f95a9146f57b26800a

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - matplotlib-base >=3.6.0
    - Jinja2 >=3.1.0
    - numpy >=1.26.0
    - pandas >=1.4.0
    - plotly >=5.11.0
    - python >={{ python_min }}
    - scipy >=1.10.0
    - screeninfo >=0.8.1
    - seaborn >=0.12.0

test:
  requires:
    - python {{ python_min }}
  source_files:
    - tests
  imports:
    - klib

about:
  home: https://github.com/akanz1/klib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easy to use Python library of customized functions for cleaning and analyzing data.
  dev_url: https://github.com/akanz1/klib

extra:
  recipe-maintainers:
    - akanz1
