{% set name = "klib" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a19e67fe6c847f8e68e53c4242ce58ec13e8ba68951e5e222a80cb828911759

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - matplotlib >=3.0.3
    - numpy >=1.16.3
    - pandas >=1.1.2
    - seaborn >=0.11.1
    - scikit-learn >=0.23.1
    - scipy >=1.1.0
  run:
    - python >=3.7
    - matplotlib-base >=3.0.3
    - numpy >=1.16.3
    - pandas >=1.1.2
    - seaborn >=0.11.1
    - scikit-learn >=0.23.1
    - scipy >=1.1.0

test:
  imports:
    - klib
    - klib.tests

about:
  home: https://github.com/akanz1/klib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Customized data preprocessing functions for frequent tasks.
  dev_url: https://github.com/akanz1/klib

extra:
  recipe-maintainers:
    - akanz1
