{% set name = "klib" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ec0d1ab8486a65381a73fc391d37a8e5b109bd44c07c44f7a2c66139eb77cb8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - poetry-core
  run:
    - matplotlib-base >=3.0.3
    - numpy >=1.16.3
    - pandas >=1.2.0
    - plotly >=5.2.2
    - python >=3.8
    - scipy >=1.1.0
    - screeninfo >=0.8.1
    - seaborn >=0.11.2

test:
  source_files:
    - tests
  imports:
    - klib

about:
  home: https://github.com/akanz1/klib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easy to use Python library of customized functions for cleaning and analyzing data.
  dev_url: https://github.com/akanz1/klib

extra:
  recipe-maintainers:
    - akanz1
