{% set name = "klib" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c41034605b13097806d3977426283171643dd66f033a9e3529b96dc698f475c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - matplotlib-base >=3.9.0
    - Jinja2 >=3.1.0
    - numpy >=2.0.0
    - pandas >=1.4,<4.0
    - plotly >=5.24.0
    - python >={{ python_min }}
    - scipy >=1.14.0
    - screeninfo >=0.8.1
    - seaborn >=0.13.0

test:
  requires:
    - python {{ python_min }}
  source_files:
    - tests
  imports:
    - klib

about:
  home: https://github.com/akanz1/klib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easy to use Python library of customized functions for cleaning and analyzing data.
  dev_url: https://github.com/akanz1/klib

extra:
  recipe-maintainers:
    - akanz1
